# stack on travis ci document
# https://docs.haskellstack.org/en/stable/travis_ci/

dist: xenial

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev
      - python3

git:
  depth: 50

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ./scripts/runTest.py

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- git log
- ./scripts/runTest.py
