{
  frontend: {
    test: /^client//,
    script: echo 'not implemented' >&2
  },
  backend: {
    test: /^src//,
    script: stack --no-terminal test
  },
  build: {
    test: /^scripts//,
    script: ./scripts/test-helper.py
  }
}
